-- MySQL Script generated by MySQL Workbench
-- lun. 04 mai 2015 09:20:45 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

--
-- MySQL 5.5.41
-- Mon, 18 May 2015 07:39:03 +0000
--

CREATE TABLE `attribute` (
  `id` bigint(20) unsigned not null auto_increment,
  `attribute_type_id` bigint(20) unsigned not null,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `fk_attribute_attribute_type1_idx` (`attribute_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=6;


CREATE TABLE `attribute_i18n` (
  `attribute_id` bigint(20) unsigned not null,
  `i18n_id` varchar(10) not null,
  `value` varchar(45),
  PRIMARY KEY (`attribute_id`,`i18n_id`),
  KEY `fk_attribute_i18n_attribute1_idx` (`attribute_id`),
  KEY `fk_attribute_i18n_language1_idx` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `attribute_type` (
  `id` bigint(20) unsigned not null auto_increment,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=3;


CREATE TABLE `attribute_type_i18n` (
  `attribute_type_id` bigint(20) unsigned not null,
  `i18n_id` varchar(10) not null,
  `value` varchar(45),
  PRIMARY KEY (`attribute_type_id`,`i18n_id`),
  KEY `fk_attribute_type_i18n_attribute_type1_idx` (`attribute_type_id`),
  KEY `fk_attribute_type_i18n_language1_idx` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `brand` (
  `id` bigint(20) unsigned not null auto_increment,
  `name` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=4;


CREATE TABLE `bundle` (
  `id` bigint(20) unsigned not null auto_increment,
  `bundle_variant` bigint(20) unsigned not null,
  `product_id` bigint(20) unsigned not null,
  `variant_id` bigint(20) unsigned,
  `quantity` int(11) unsigned not null default '1',
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `fk_product_has_variant_variant1_idx` (`bundle_variant`),
  KEY `fk_product_has_variant_product1_idx` (`product_id`),
  KEY `fk_bundle_variant1_idx` (`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE `cross_selling` (
  `variant_id_1` bigint(20) unsigned not null,
  `variant_id_2` bigint(20) unsigned not null,
  `discount_id` bigint(20) unsigned not null,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`variant_id_1`,`variant_id_2`),
  KEY `fk_variant_has_variant_variant2_idx` (`variant_id_2`),
  KEY `fk_variant_has_variant_variant1_idx` (`variant_id_1`),
  KEY `fk_cross_selling_discount1_idx` (`discount_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `discount` (
  `id` bigint(20) unsigned not null auto_increment,
  `percent` float not null,
  `start_date` datetime not null,
  `end_date` datetime not null,
  `percent_vip` float not null,
  `start_date_vip` datetime not null,
  `end_date_vip` datetime not null,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=2;


CREATE TABLE `logistic_strategy` (
  `id` bigint(20) unsigned not null auto_increment,
  `stockout` tinyint(1) unsigned not null default '0',
  `preorder` tinyint(1) unsigned not null default '0',
  `delivery_date` timestamp,
  `real_stock` tinyint(1) unsigned not null default '0',
  `alert_stock` smallint(5) unsigned not null default '0',
  `direct_delivery` tinyint(1) unsigned not null default '0',
  `supplier_id` bigint(20) unsigned not null,
  `additional_delay` tinyint(3) unsigned not null default '0',
  `just_in_time` tinyint(1) unsigned not null default '0',
  `temporary_stockout` tinyint(1) unsigned not null,
  PRIMARY KEY (`id`),
  KEY `fk_stock_strategy_supplier1_idx` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=3;


CREATE TABLE `logistic_strategy_i18n` (
  `logistic_strategy_id` bigint(20) unsigned not null,
  `i18n_id` varchar(16) not null,
  `message` varchar(5000),
  PRIMARY KEY (`logistic_strategy_id`,`i18n_id`),
  KEY `fk_stock_strategy_i18n_language1_idx` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `media` (
  `id` bigint(20) unsigned not null auto_increment,
  `file` varchar(255) not null,
  `media_type_id` bigint(20) unsigned not null,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `fk_media_media_type1_idx` (`media_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=5;


CREATE TABLE `media_i18n` (
  `media_id` bigint(20) unsigned not null,
  `i18n_id` varchar(16) not null,
  `title` varchar(255),
  PRIMARY KEY (`media_id`,`i18n_id`),
  KEY `fk_media_i18n_media1_idx` (`media_id`),
  KEY `fk_media_i18n_language1` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `media_type` (
  `id` bigint(20) unsigned not null auto_increment,
  `created_at` timestamp not null default '0000-00-00 00:00:00',
  `updated_at` timestamp not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=3;


CREATE TABLE `media_type_i18n` (
  `media_type_id` bigint(20) unsigned not null,
  `i18n_id` varchar(16) not null,
  `title` varchar(255),
  PRIMARY KEY (`media_type_id`,`i18n_id`),
  KEY `fk_media_i18n_copy1_media_type1_idx` (`media_type_id`),
  KEY `fk_media_i18n_language10` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `product` (
  `id` bigint(20) unsigned not null auto_increment,
  `exclude_discount_code` tinyint(1) unsigned not null default '0',
  `force_secure` tinyint(1) unsigned not null default '0',
  `archived` tinyint(1) unsigned not null default '0',
  `top_product` tinyint(1) unsigned not null default '0',
  `exclude_from_google` tinyint(1) unsigned not null default '0',
  `link_brand_product` varchar(255),
  `link_product_test` varchar(255),
  `available` tinyint(1) unsigned not null default '0',
  `available_date` datetime not null,
  `alternative_product` bigint(20) unsigned,
  `brand_id` bigint(20) unsigned not null,
  `supplier_id` bigint(20) unsigned not null,
  `google_category_id` bigint(20) unsigned not null,
  `stats_category_id` bigint(20) unsigned not null,
  `accountant_category_id` bigint(20) unsigned not null,
  `base_price` decimal(15,4) unsigned not null,
  `is_pack` tinyint(1) unsigned not null default '0',
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `fk_product_product1_idx` (`alternative_product`),
  KEY `fk_product_brand1_idx` (`brand_id`),
  KEY `fk_product_supplier1_idx` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=3;


CREATE TABLE `product_i18n` (
  `product_id` bigint(20) unsigned not null,
  `i18n_id` varchar(10) not null,
  `short_description` varchar(2000),
  `long_description` varchar(7000),
  `comment` varchar(4000),
  `page_title` varchar(750),
  `name` varchar(500) not null,
  `infos_shipping` varchar(5000),
  `meta_description` varchar(2000),
  `meta_keywords` varchar(500),
  PRIMARY KEY (`product_id`,`i18n_id`),
  KEY `fk_product_i18n_product1_idx` (`product_id`),
  KEY `fk_product_i18n_language1_idx` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `product_media` (
  `product_id` bigint(20) unsigned not null,
  `media_id` bigint(20) unsigned not null,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`product_id`,`media_id`),
  KEY `fk_product_has_media_media1_idx` (`media_id`),
  KEY `fk_product_has_media_product_idx` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `supplier` (
  `id` bigint(20) unsigned not null auto_increment,
  `name` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=2;


CREATE TABLE `variant` (
  `id` bigint(20) unsigned not null auto_increment,
  `product_id` bigint(20) unsigned not null,
  `code` varchar(15),
  `supplier_code` varchar(100),
  `barcode` varchar(100),
  `order` int(11) unsigned,
  `visible` tinyint(1) unsigned not null default '0',
  `primary` tinyint(1) unsigned not null default '0',
  `top_selling` tinyint(1) unsigned not null default '0',
  `height` int(11) unsigned,
  `width` int(11) unsigned,
  `length` int(11) unsigned,
  `weight` int(11) unsigned,
  `logistic_strategy_id` bigint(20) unsigned not null,
  `last_inventory_date` datetime not null,
  `shipping_period_start` datetime not null,
  `shipping_period_end` datetime not null,
  `selling_period_start` datetime not null,
  `selling_period_end` datetime not null,
  `discount_id` bigint(20) unsigned,
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `fk_attribute_has_product_product1_idx` (`product_id`),
  KEY `fk_variant_discount1_idx` (`discount_id`),
  KEY `fk_variant_stock_strategy1_idx` (`logistic_strategy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=6;


CREATE TABLE `variant_attribute` (
  `variant_id` bigint(20) unsigned not null,
  `attribute_id` bigint(20) unsigned not null,
  `extra_cost` decimal(15,4),
  `created_at` datetime not null default '0000-00-00 00:00:00',
  `updated_at` datetime not null default '0000-00-00 00:00:00',
  PRIMARY KEY (`variant_id`,`attribute_id`),
  KEY `fk_variation_has_attribute_attribute1_idx` (`attribute_id`),
  KEY `fk_variation_has_attribute_variation1_idx` (`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `variant_i18n` (
  `variant_id` bigint(20) unsigned not null,
  `i18n_id` varchar(10) not null,
  `description` varchar(8000),
  PRIMARY KEY (`variant_id`,`i18n_id`),
  KEY `fk_variation_i18n_variation1_idx` (`variant_id`),
  KEY `fk_variant_i18n_language1_idx` (`i18n_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `message` (`id`, `message_group_id`, `source`, `created_at`, `updated_at`) VALUES
  ('660', '2', 'navbar_product', '2015-05-04 12:16:47', '2015-05-04 12:16:47'),
  ('661', '2', 'navbar_product_list', '2015-05-04 12:42:51', '2015-05-04 12:42:51'),
  ('662', '2', 'navbar_product_add', '2015-05-04 12:44:47', '2015-05-04 12:44:47'),
  ('663', '2', 'product_variant_count', '2015-05-05 03:20:37', '2015-05-05 03:20:37'),
  ('664', '2', 'product_tab_product', '2015-05-05 03:44:56', '2015-05-05 03:44:56'),
  ('665', '2', 'product_tab_attribute', '2015-05-05 03:45:21', '2015-05-11 07:43:58'),
  ('666', '2', 'product_tab_description', '2015-05-05 03:45:43', '2015-05-11 07:43:58'),
  ('667', '2', 'product_tab_prices', '2015-05-05 03:46:28', '2015-05-11 07:43:58'),
  ('668', '2', 'product_tab_logistic', '2015-05-05 03:49:28', '2015-05-11 07:43:58'),
  ('669', '2', 'product_tab_cross_selling', '2015-05-05 03:50:02', '2015-05-11 07:43:58'),
  ('670', '2', 'product_tab_discount', '2015-05-05 03:50:20', '2015-05-11 07:43:58'),
  ('671', '2', 'product_tab_media', '2015-05-05 03:50:39', '2015-05-11 07:43:58'),
  ('672', '2', 'product_tab_variant_list', '2015-05-07 12:33:14', '2015-05-11 07:43:58'),
  ('673', '2', 'product_tab_variant_price', '2015-05-07 12:33:44', '2015-05-11 07:43:58'),
  ('674', '2', 'btn_reset', '2015-05-07 01:12:13', '2015-05-11 07:43:58');

INSERT INTO `message_i18n` (`message_id`, `i18n_id`, `translation`) VALUES
  ('660', 'en', 'Products'),
  ('660', 'fr', 'Produits'),
  ('661', 'en', 'Products list'),
  ('661', 'fr', 'Liste des produits'),
  ('662', 'en', 'Add a product'),
  ('662', 'fr', 'Ajouter un produit'),
  ('663', 'en', '{n, plural, =0{No variation} =1{1 variation} other{# variations}}'),
  ('663', 'fr', '{n, plural, =0{Pas de variation} =1{1 variation} other{# variations}}'),
  ('664', 'en', 'Product'),
  ('664', 'fr', 'Produit'),
  ('665', 'en', 'Attribute'),
  ('665', 'fr', 'Attribut'),
  ('666', 'en', 'Descriptions'),
  ('666', 'fr', 'Descriptions'),
  ('667', 'en', 'Prices & buy prices'),
  ('667', 'fr', 'Tarifs & prix d\'achat'),
  ('668', 'en', 'Stock & logistic'),
  ('668', 'fr', 'Stock & logistique'),
  ('669', 'en', 'Cross selling'),
  ('669', 'fr', 'Cross selling'),
  ('670', 'en', 'Discounts'),
  ('670', 'fr', 'Promotions'),
  ('671', 'en', 'Medias'),
  ('671', 'fr', 'Médias'),
  ('672', 'en', 'Variant list'),
  ('672', 'fr', 'Liste des variations'),
  ('673', 'en', 'Variant prices'),
  ('673', 'fr', 'Prix des variations'),
  ('674', 'en', 'Reset'),
  ('674', 'fr', 'Annuler');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
