-- MySQL Script generated by MySQL Workbench
-- mar. 29 déc. 2015 15:45:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `country` (
  `id` VARCHAR(2) NOT NULL,
  `iso3` VARCHAR(3) NULL,
  `numcode` SMALLINT(6) UNSIGNED NULL,
  `phonecode` SMALLINT(5) UNSIGNED NULL,
  `created_at` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `country_i18n`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `country_i18n` (
  `country_id` VARCHAR(2) NOT NULL,
  `i18n_id` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`country_id`, `i18n_id`),
  INDEX `fk_country_lang_language1_idx` (`i18n_id` ASC),
  CONSTRAINT `fk_country_lang_tax`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_lang_language1`
    FOREIGN KEY (`i18n_id`)
    REFERENCES `language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tax` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rate` DECIMAL(10,3) NOT NULL,
  `created_at` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_i18n`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tax_i18n` (
  `tax_id` BIGINT UNSIGNED NOT NULL,
  `i18n_id` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tax_id`, `i18n_id`),
  INDEX `fk_tax_lang_language1_idx` (`i18n_id` ASC),
  CONSTRAINT `fk_tax_lang_tax`
    FOREIGN KEY (`tax_id`)
    REFERENCES `tax` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_lang_language1`
    FOREIGN KEY (`i18n_id`)
    REFERENCES `language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tax_country` (
  `tax_id` BIGINT UNSIGNED NOT NULL,
  `country_id` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`tax_id`, `country_id`),
  INDEX `fk_tax_has_country_country1_idx` (`country_id` ASC),
  INDEX `fk_tax_has_country_tax1_idx` (`tax_id` ASC),
  CONSTRAINT `fk_tax_has_country_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `tax` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_has_country_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


