#!/usr/bin/env php
<?php
/**
 * @copyright Copyright (c) 2015 Kévin Walter <walkev13@gmail.com> - Kalibao
 * @license https://github.com/kalibao/kalibao-framework/blob/master/LICENSE
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../kalibao/common/config/bootstrap.php');
require(__DIR__ . '/../kalibao/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../kalibao/common/config/main.php'),
    require(__DIR__ . '/../kalibao/common/config/main-local.php'),
    require(__DIR__ . '/../kalibao/console/config/main.php'),
    require(__DIR__ . '/../kalibao/console/config/main-local.php')
);

$application = new \kalibao\console\components\console\Application($config);
$exitCode = $application->run();

exit($exitCode);